server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/408212480/conifgRepo
          #          searchPaths: licensingservice,organizationservice
          username: 408212480@qq.com
          password: 83260016change